version: "3.5"

services:
  php:
    build:
      context: ./docker-images/php/
      dockerfile: Dockerfile
    volumes: &readWriteAppVolume
      - ./app:/opt/app
    working_dir: /opt/app

  composer:
    build:
      context: ./docker-images/php/
      dockerfile: Dockerfile
    volumes: *readWriteAppVolume
    working_dir: /opt/app
    entrypoint: php ./composer.phar